/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.austral.dissis.chess

import Chess.Game
import Chess.Piece
import Chess.Piecies
import Chess.*
import edu.austral.dissis.chess.gui.*
import javafx.application.Application
import javafx.application.Application.launch
import javafx.scene.Scene
import javafx.stage.Stage



fun main() {
    Application.launch(MyChessGameApplication::class.java)
}

class MyChessGameApplication : AbstractChessGameApplication() {

    override val gameEngine: GameEngine = MyChess();
    override val imageResolver: ImageResolver = CachedImageResolver(DefaultImageResolver())
}