/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.austral.dissis.chess

import edu.austral.dissis.chess.gui.*
import javafx.application.Application


fun main() {
    Application.launch(MyChessGameApplication::class.java)
}

class MyChessGameApplication : AbstractChessGameApplication() {

    override val gameEngine: GameEngine = MyChess();
    override val imageResolver: ImageResolver = CachedImageResolver(DefaultImageResolver())
}